basePath: /
host: localhost:8080
info:
  contact:
    email: evgen.myroshnykov@gmail.com
  description: Educational project
  title: Post app with authorization
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
